--liquibase formatted sql

--changeset jirkavrba:create-collectibles-table
create table collectibles
(
    "id"          int          not null generated by default as identity primary key,
    "emoji"       varchar(8)   not null,
    "name"        varchar(128) not null,
    "description" varchar(512) not null,
    "value"       int          not null,
    "quantity"    int          not null
);

--changeset jirkavrba:create-score-table
create table score
(
    "id"      int    not null generated by default as identity primary key,
    "user_id" bigint not null,
    "points"  int    not null
);