--liquibase formatted sql

--changeset jirkavrba:create-collectibles-table
create table collectibles
(
    "id"          int          not null generated by default as identity primary key,
    "emoji"       varchar(8)   not null,
    "name"        varchar(128) not null,
    "description" varchar(512) not null,
    "value"       int          not null,
    "quantity"    int          not null
);

--changeset jirkavrba:create-score-table
create table score
(
    "id"      int    not null generated by default as identity primary key,
    "user_id" bigint not null,
    "points"  int    not null
);

--changelog jirkavrba:import-collectibles
insert into collectibles ("emoji", "name", "description", "value", "quantity")
values ('🎃', 'Jack-O-Lantern', 'Hmm looks stunning', 2, 5),
       ('👻', 'A friendly ghost', 'Will ghost you on Discord', 4, 5),
       ('🍬', 'A tasty candy', 'Nom nom nom', 1, 10),
       ('💀', 'An authentic human skull', 'Wonder where it came from', 2, 8),
       ('⛓️ ', 'A real metal chain, wow', 'Can I make a chainsaw out of this?', 2, 4),
       ('🍫', 'A chocolate bar', 'Love the taste', 1, 10),
       ('🕯️ ', 'A candle', 'Finally some source of light', 1, 10),
       ('🗡️ ', 'A really sharp dagger', 'Stab stab', 2, 8),
       ('🔮', 'A magical crystal ball', 'You can see the future', 5, 2),
       ('🍭', 'A lollipop', 'Sweet & tasty', 1, 10),
       ('🕷️ ', 'A pet spider', 'I hope it doesn''t bite', 2, 6),
       ('🪱', 'A worm', 'Tasty!', 2, 4),
       ('⚰️', 'A coffin', 'What a nice sleeping bed', 3, 2),
       ('👽', 'An alien friend', 'Area 51 must have lost this one', 4, 2),
       ('🫀', 'An authentic human hearth', 'It''s still beating, ew', 3, 8),
       ('🪲', 'A beetle', 'Crunchy snack!', 2, 5),
       ('🤡', 'A clown', 'Provides plumbing services', 2, 4),
       ('🪳', 'A cockroach', 'Immortal buddy', 2, 4),
       ('🦇', 'A bat', 'Ozzy Osbourne''s favorite snack', 2, 4),
       ('🐺', 'A wolf', 'Woof woof buddy', 3, 2),
       ('🐈', 'A cat', 'Meow', 2, 4),
       ('🦄', 'An unicorn', 'Shiny!', 5, 2),
       ('🧟', 'A zombie buddy', 'Watches Netflix all day', 3, 2),
       ('😈', 'A devil', 'Will provide bad advice, cool guy though', 3, 2),
       ('🥀', 'A dead flower', 'Sad', 4, 2),
       ('👑', 'A crown', 'King/Queen, you dropped this', 10, 1),
       ('🍍', 'A pineapple', 'I will put this one on pizza for sure', 3, 5),
       ('🦢', 'A swan?', 'Yeah, there is no goose emoji yet :(', 5, 5),
       ('📜', 'A haiku', 'I''ve seen this one before', 5, 5),
       ('🎫', 'A ticket', 'Wanna watch a horror movie together?', 3, 5),
       ('🍵', 'A tea', 'Drink it while it''s still warm', 2, 5),
       ('🍹', 'A fancy drink', 'Post it to <#697048737834598471>', 3, 4),
       ('🕵️ ', 'A detective', 'He will help you with your clues for codenames', 4, 2),
       ('💣', 'A bomb', 'The time is ticking!', 3, 5),
       ('✨', 'A sparkle', 'Nice and shiny', 1, 5),
       ('🌠', 'A falling star', 'Make a wish!', 1, 10);

--changelog jirkavrba:add-collection-to-score-table
alter table score
    add column "collection" varchar(2048) default '';